name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.0.4
homepage: https://github.com/llfbandit/record/tree/master/record_android
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: # ^1.0.2
    #path: ../record_platform_interface
    git:
      url: https://github.com/vuihoc-edtech/record
      ref: master
      path: record_platform_interface

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
